/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FootALink: typeof import('./components/foot-note/FootALink.vue')['default']
    FootNote: typeof import('./components/foot-note/FootNote.vue')['default']
    HeaderBar: typeof import('./components/HeaderBar.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NotFound: typeof import('./components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
